"""Validate invoice evidence against saved bindings and confirmed upgrade quotes.

No Stripe writes, transaction commits, or transition command dependencies.
"""

from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation

from sqlalchemy import select

from app.models.subscription_change import SubscriptionChange as Change
from app.models.subscription_upgrade import SubscriptionUpgrade as Upgrade
from app.services import billing_provider as billing
from app.services.billing_provider import Error


def ref(value):
    return value.get("id") if isinstance(value, dict) else value


def subscription_id(value):
    parent = value.get("parent") or {}
    return ref(
        (parent.get("subscription_details") or {}).get("subscription")
        or value.get("subscription")
    )


def metadata(value):
    return (
        (value.get("parent") or {}).get("subscription_details")
        or value.get("subscription_details")
        or {}
    ).get("metadata") or {}


def stamp(value, *, optional=True):
    if value is None and optional:
        return None
    if type(value) is not int or value < 0:
        raise Error("Stripe returned an invalid invoice timestamp.")
    try:
        return datetime.fromtimestamp(value, timezone.utc)
    except (ValueError, OverflowError, OSError):
        raise Error("Stripe returned an invalid invoice timestamp.") from None


def expected_invoice_price(db, checkout, period_start):
    """Historical full-period invoices follow both scheduled and paid upgrade bindings."""
    from app.models.subscription_upgrade import SubscriptionUpgrade

    events = [
        (billing.utc(c.effective_at), c.source_price_id, c.target_price_id)
        for c in db.scalars(
            select(Change).where(
                Change.checkout_id == checkout.id, Change.applied_at.is_not(None)
            )
        )
    ]
    events += [
        (billing.utc(u.proration_at), u.source_price_id, u.target_price_id)
        for u in db.scalars(
            select(SubscriptionUpgrade).where(
                SubscriptionUpgrade.checkout_id == checkout.id,
                SubscriptionUpgrade.applied_at.is_not(None),
            )
        )
    ]
    events.sort(key=lambda e: e[0])
    if not events or period_start is None:
        return checkout.price_id
    price = events[0][1]
    for effective, source, target in events:
        if period_start >= effective:
            price = target
    return price


def snapshot(value, checkout, row, *, preview=False):
    """Validate the complete invoice, retaining only payment-relevant fields."""
    if (
        value.get("object") != "invoice"
        or value.get("livemode") is not False
        or ref(value.get("customer")) != checkout.customer_id
        or subscription_id(value) != checkout.subscription_id
    ):
        raise billing.Error("Upgrade invoice ownership could not be verified.", 409)
    currency = row.quote["currency"]
    if (
        value.get("currency") != currency
        or value.get("collection_method") != "charge_automatically"
    ):
        raise billing.Error(
            "Upgrade invoice currency or collection method does not match.", 409
        )
    if not preview and value.get("billing_reason") != "subscription_update":
        raise billing.Error(
            "Expected an invoice generated by this subscription update.", 409
        )
    if (
        value.get("discounts")
        or value.get("total_discount_amounts")
        or value.get("default_tax_rates")
        or (value.get("automatic_tax") or {}).get("enabled")
        or value.get("starting_balance", 0)
        or value.get("ending_balance", 0)
        or value.get("amount_shipping", 0)
        or value.get("paid_out_of_band")
        or value.get("amount_paid_off_stripe", 0)
        or value.get("post_payment_credit_notes_amount", 0)
        or value.get("pre_payment_credit_notes_amount", 0)
        or value.get("amount_overpaid", 0)
    ):
        raise billing.Error(
            "Discounts, balances, manual settlement, or invoice adjustments require review.",
            409,
        )
    values = value.get("lines") or {}
    lines = values.get("data") or []
    if values.get("has_more") is not False or len(lines) != 2:
        raise billing.Error(
            "Expected exactly the complete unused-time credit and upgrade charge.", 409
        )
    normalized = []
    for line in lines:
        details = (line.get("parent") or {}).get("subscription_item_details") or {}
        price = ref(
            (((line.get("pricing") or {}).get("price_details") or {}).get("price"))
            or line.get("price")
        )
        try:
            quantity = Decimal(
                str(
                    line.get("quantity_decimal")
                    if line.get("quantity_decimal") is not None
                    else line.get("quantity")
                )
            )
        except InvalidOperation:
            quantity = Decimal(0)
        if (
            details.get("proration", line.get("proration")) is not True
            or quantity != 1
            or ref(details.get("subscription") or line.get("subscription"))
            != checkout.subscription_id
            or ref(details.get("subscription_item") or line.get("subscription_item"))
            != row.item_id
            or line.get("currency") != currency
            or type(line.get("amount")) is not int
        ):
            raise billing.Error(
                "Upgrade invoice line ownership, quantity, or proration is unverified.",
                409,
            )
        start, end = (
            (line.get("period") or {}).get("start"),
            (line.get("period") or {}).get("end"),
        )
        if start != int(billing.utc(row.proration_at).timestamp()) or end != int(
            billing.utc(row.period_end).timestamp()
        ):
            raise billing.Error(
                "Upgrade proration dates differ from the confirmed quote.", 409
            )
        normalized.append(
            {"price": price, "amount": line["amount"], "start": start, "end": end}
        )
    by_price = {l["price"]: l for l in normalized}
    if (
        len(by_price) != 2
        or set(by_price) != {row.source_price_id, row.target_price_id}
        or by_price[row.source_price_id]["amount"] > 0
        or by_price[row.target_price_id]["amount"] <= 0
    ):
        raise billing.Error(
            "Upgrade invoice must credit the saved source price and charge the target price.",
            409,
        )
    total = value.get("total")
    due = value.get("amount_due")
    if (
        type(total) is not int
        or type(due) is not int
        or total <= 0
        or due != total
        or sum(l["amount"] for l in normalized) != total
    ):
        raise billing.Error(
            "Upgrade total must match its credit and charge without other adjustments.",
            409,
        )
    return {
        "currency": currency,
        "amount_due": due,
        "total": total,
        "lines": sorted(normalized, key=lambda l: l["price"]),
    }


def invoice_issue(db, checkout, value):
    row = db.scalar(
        select(Upgrade).where(
            Upgrade.invoice_id == value.get("id"), Upgrade.checkout_id == checkout.id
        )
    )
    if not row:
        return None
    try:
        if snapshot(value, checkout, row) != row.quote:
            raise billing.Error(
                "The invoice differs from the confirmed upgrade quote.", 409
            )
        if value.get("status") == "paid" and (
            value.get("amount_paid") != row.quote["amount_due"]
            or value.get("amount_remaining") != 0
            or not (value.get("status_transitions") or {}).get("paid_at")
        ):
            raise billing.Error(
                "Upgrade settlement is incomplete or inconsistent.", 409
            )
        return {"issue": None, "start": row.proration_at, "end": row.period_end}
    except billing.Error as exc:
        return {"issue": str(exc), "start": row.proration_at, "end": row.period_end}
